package models

// DriversData contains all drivers with their complete information including images
var DriversData = []Driver{
	{
		DriverID:        "albon",
		PermanentNumber: "23",
		Code:            "ALB",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/williams/alealb01/2025williamsalealb01right.webp",
		GivenName:       "Alexander",
		FamilyName:      "Albon",
		DateOfBirth:     "1996-03-23",
		Nationality:     "Thai",
		Team:            "Williams",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "alonso",
		PermanentNumber: "14",
		Code:            "ALO",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/astonmartin/feralo01/2025astonmartinferalo01right.webp",
		GivenName:       "Fernando",
		FamilyName:      "Alonso",
		DateOfBirth:     "1981-07-29",
		Nationality:     "Spanish",
		Team:            "Aston Martin",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "antonelli",
		PermanentNumber: "12",
		Code:            "ANT",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/mercedes/andant01/2025mercedesandant01right.webp",
		GivenName:       "Andrea Kimi",
		FamilyName:      "Antonelli",
		DateOfBirth:     "2006-08-25",
		Nationality:     "Italian",
		Team:            "Mercedes",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "paul_aron",
		PermanentNumber: "61",
		Code:            "ARO",
		Image:           "https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMi9hcm8ucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=",
		GivenName:       "Paul",
		FamilyName:      "Aron",
		DateOfBirth:     "2004-02-04",
		Nationality:     "Estonian",
		Team:            "Alpine F1 Team",
		DriverType:      "Test Driver",
	},
	{
		DriverID:        "bearman",
		PermanentNumber: "87",
		Code:            "BEA",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/haas/olibea01/2025haasolibea01right.webp",
		GivenName:       "Oliver",
		FamilyName:      "Bearman",
		DateOfBirth:     "2005-05-08",
		Nationality:     "British",
		Team:            "Haas",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "bortoleto",
		PermanentNumber: "5",
		Code:            "BOR",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/kicksauber/gabbor01/2025kicksaubergabbor01right.webp",
		GivenName:       "Gabriel",
		FamilyName:      "Bortoleto",
		DateOfBirth:     "2004-10-14",
		Nationality:     "Brazilian",
		Team:            "Kick Sauber",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "luke_browning",
		PermanentNumber: "46",
		Code:            "BRO",
		Image:           "https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMy9icm8ucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=",
		GivenName:       "Luke",
		FamilyName:      "Browning",
		DateOfBirth:     "2002-01-31",
		Nationality:     "British",
		Team:            "Williams",
		DriverType:      "Test Driver",
	},
	{
		DriverID:        "colapinto",
		PermanentNumber: "43",
		Code:            "COL",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/alpine/fracol01/2025alpinefracol01right.webp",
		GivenName:       "Franco",
		FamilyName:      "Colapinto",
		DateOfBirth:     "2003-05-27",
		Nationality:     "Argentine",
		Team:            "Alpine F1 Team",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "jak_crawford",
		PermanentNumber: "35",
		Code:            "CRA",
		Image:           "https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMi9jcmEucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=",
		GivenName:       "Jak",
		FamilyName:      "Crawford",
		DateOfBirth:     "2005-05-02",
		Nationality:     "American",
		Team:            "Aston Martin",
		DriverType:      "Test Driver",
	},
	{
		DriverID:        "doohan",
		PermanentNumber: "7",
		Code:            "DOO",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/alpine/jacdoo01/2025alpinejacdoo01right.webp",
		GivenName:       "Jack",
		FamilyName:      "Doohan",
		DateOfBirth:     "2003-01-20",
		Nationality:     "Australian",
		Team:            "Alpine F1 Team",
		DriverType:      "Reserve Driver",
	},
	{
		DriverID:        "gasly",
		PermanentNumber: "10",
		Code:            "GAS",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/alpine/piegas01/2025alpinepiegas01right.webp",
		GivenName:       "Pierre",
		FamilyName:      "Gasly",
		DateOfBirth:     "1996-02-07",
		Nationality:     "French",
		Team:            "Alpine F1 Team",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "hadjar",
		PermanentNumber: "6",
		Code:            "HAD",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/racingbulls/isahad01/2025racingbullsisahad01right.webp",
		GivenName:       "Isack",
		FamilyName:      "Hadjar",
		DateOfBirth:     "2004-09-28",
		Nationality:     "French",
		Team:            "Racing Bulls",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "hamilton",
		PermanentNumber: "44",
		Code:            "HAM",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/ferrari/lewham01/2025ferrarilewham01right.webp",
		GivenName:       "Lewis",
		FamilyName:      "Hamilton",
		DateOfBirth:     "1985-01-07",
		Nationality:     "British",
		Team:            "Ferrari",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "ryo_hirakawa",
		PermanentNumber: "50",
		Code:            "HIR",
		Image:           "https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS1hZmZpbGlhdGVzL2hyay5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjUwMH19fQ==",
		GivenName:       "Ryo",
		FamilyName:      "Hirakawa",
		DateOfBirth:     "1994-03-07",
		Nationality:     "Japanese",
		Team:            "Haas",
		DriverType:      "Test Driver",
	},
	{
		DriverID:        "hulkenberg",
		PermanentNumber: "27",
		Code:            "HUL",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/kicksauber/nichul01/2025kicksaubernichul01right.webp",
		GivenName:       "Nico",
		FamilyName:      "Hülkenberg",
		DateOfBirth:     "1987-08-19",
		Nationality:     "German",
		Team:            "Kick Sauber",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "ayumu_iwasa",
		PermanentNumber: "15",
		Code:            "IWA",
		Image:           "https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS1hZmZpbGlhdGVzL2l3YS5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjUwMH19fQ==",
		GivenName:       "Ayumu",
		FamilyName:      "Iwasa",
		DateOfBirth:     "2001-09-22",
		Nationality:     "Japanese",
		Team:            "Racing Bulls",
		DriverType:      "Test Driver",
	},
	{
		DriverID:        "lawson",
		PermanentNumber: "30",
		Code:            "LAW",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/racingbulls/lialaw01/2025racingbullslialaw01right.webp",
		GivenName:       "Liam",
		FamilyName:      "Lawson",
		DateOfBirth:     "2002-02-11",
		Nationality:     "New Zealander",
		Team:            "Racing Bulls",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "leclerc",
		PermanentNumber: "16",
		Code:            "LEC",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/ferrari/chalec01/2025ferrarichalec01right.webp",
		GivenName:       "Charles",
		FamilyName:      "Leclerc",
		DateOfBirth:     "1997-10-16",
		Nationality:     "Monegasque",
		Team:            "Ferrari",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "arthur_leclerc",
		PermanentNumber: "39",
		Code:            "ALE",
		Image:           "https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyMi9kcml2ZXJzL2hlYWRzaG90cy9mMy9hbGUucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=",
		GivenName:       "Arthur",
		FamilyName:      "Leclerc",
		DateOfBirth:     "2000-10-14",
		Nationality:     "Monegasque",
		Team:            "Ferrari",
		DriverType:      "Test Driver",
	},
	{
		DriverID:        "arvid_lindblad",
		PermanentNumber: "36",
		Code:            "LIN",
		Image:           "https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMy9saW4ucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=",
		GivenName:       "Arvid",
		FamilyName:      "Lindblad",
		DateOfBirth:     "2007-08-08",
		Nationality:     "British",
		Team:            "Racing Bulls",
		DriverType:      "Test Driver",
	},
	{
		DriverID:        "norris",
		PermanentNumber: "4",
		Code:            "NOR",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/mclaren/lannor01/2025mclarenlannor01right.webp",
		GivenName:       "Lando",
		FamilyName:      "Norris",
		DateOfBirth:     "1999-11-13",
		Nationality:     "British",
		Team:            "McLaren",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "ocon",
		PermanentNumber: "31",
		Code:            "OCO",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/haas/estoco01/2025haasestoco01right.webp",
		GivenName:       "Esteban",
		FamilyName:      "Ocon",
		DateOfBirth:     "1996-09-17",
		Nationality:     "French",
		Team:            "Haas",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "patricio_o_ward",
		PermanentNumber: "5",
		Code:            "OWA",
		Image:           "https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS1hZmZpbGlhdGVzL293ZC5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjUwMH19fQ==",
		GivenName:       "Patricio",
		FamilyName:      "O'Ward",
		DateOfBirth:     "1999-05-06",
		Nationality:     "Mexican",
		Team:            "McLaren",
		DriverType:      "Test Driver",
	},
	{
		DriverID:        "piastri",
		PermanentNumber: "81",
		Code:            "PIA",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/mclaren/oscpia01/2025mclarenoscpia01right.webp",
		GivenName:       "Oscar",
		FamilyName:      "Piastri",
		DateOfBirth:     "2001-04-06",
		Nationality:     "Australian",
		Team:            "McLaren",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "russell",
		PermanentNumber: "63",
		Code:            "RUS",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/mercedes/georus01/2025mercedesgeorus01right.webp",
		GivenName:       "George",
		FamilyName:      "Russell",
		DateOfBirth:     "1998-02-15",
		Nationality:     "British",
		Team:            "Mercedes",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "sainz",
		PermanentNumber: "55",
		Code:            "SAI",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/williams/carsai01/2025williamscarsai01right.webp",
		GivenName:       "Carlos",
		FamilyName:      "Sainz",
		DateOfBirth:     "1994-09-01",
		Nationality:     "Spanish",
		Team:            "Williams",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "cian_shields",
		PermanentNumber: "21",
		Code:            "SHI",
		Image:           "https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMy9zaGkucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=",
		GivenName:       "Cian",
		FamilyName:      "Shields",
		DateOfBirth:     "2005-03-07",
		Nationality:     "British",
		Team:            "Aston Martin",
		DriverType:      "Test Driver",
	},
	{
		DriverID:        "stroll",
		PermanentNumber: "18",
		Code:            "STR",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/astonmartin/lanstr01/2025astonmartinlanstr01right.webp",
		GivenName:       "Lance",
		FamilyName:      "Stroll",
		DateOfBirth:     "1998-10-29",
		Nationality:     "Canadian",
		Team:            "Aston Martin",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "tsunoda",
		PermanentNumber: "22",
		Code:            "TSU",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/redbullracing/yuktsu01/2025redbullracingyuktsu01right.webp",
		GivenName:       "Yuki",
		FamilyName:      "Tsunoda",
		DateOfBirth:     "2000-05-11",
		Nationality:     "Japanese",
		Team:            "Red Bull",
		DriverType:      "Race Driver",
	},
	{
		DriverID:        "max_verstappen",
		PermanentNumber: "1",
		Code:            "VER",
		Image:           "https://media.formula1.com/image/upload/c_fill,w_720/q_auto/v1740000000/common/f1/2025/redbullracing/maxver01/2025redbullracingmaxver01right.webp",
		GivenName:       "Max",
		FamilyName:      "Verstappen",
		DateOfBirth:     "1997-09-30",
		Nationality:     "Dutch",
		Team:            "Red Bull",
		DriverType:      "Race Driver",
	},
}

// ConstructorsData contains the embedded constructors data
var ConstructorsData = []Constructor{
	{
		ConstructorID: "alpine",
		Icon:          "https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000000/common/f1/2025/alpine/2025alpinelogowhite.webp",
		Image:         "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/common/f1/2025/alpine/2025alpinecarright.webp",
		Name:          "Alpine F1 Team",
		Nationality:   "French",
		TeamColor:     "#005081",
	},
	{
		ConstructorID: "aston_martin",
		Icon:          "https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000000/common/f1/2025/astonmartin/2025astonmartinlogowhite.webp",
		Image:         "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/common/f1/2025/astonmartin/2025astonmartincarright.webp",
		Name:          "Aston Martin",
		Nationality:   "British",
		TeamColor:     "#00482C",
	},
	{
		ConstructorID: "ferrari",
		Icon:          "https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000000/common/f1/2025/ferrari/2025ferrarilogolight.webp",
		Image:         "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/common/f1/2025/ferrari/2025ferraricarright.webp",
		Name:          "Ferrari",
		Nationality:   "Italian",
		TeamColor:     "#710006",
	},
	{
		ConstructorID: "haas",
		Icon:          "https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000000/common/f1/2025/haas/2025haaslogowhite.webp",
		Image:         "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/common/f1/2025/haas/2025haascarright.webp",
		Name:          "Haas F1 Team",
		Nationality:   "American",
		TeamColor:     "#4D5052",
	},
	{
		ConstructorID: "mclaren",
		Icon:          "https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000000/common/f1/2025/mclaren/2025mclarenlogowhite.webp",
		Image:         "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/common/f1/2025/mclaren/2025mclarencarright.webp",
		Name:          "McLaren",
		Nationality:   "British",
		TeamColor:     "#863400",
	},
	{
		ConstructorID: "mercedes",
		Icon:          "https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000000/common/f1/2025/mercedes/2025mercedeslogowhite.webp",
		Image:         "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/common/f1/2025/mercedes/2025mercedescarright.webp",
		Name:          "Mercedes",
		Nationality:   "German",
		TeamColor:     "#007560",
	},
	{
		ConstructorID: "rb",
		Icon:          "https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000000/common/f1/2025/racingbulls/2025racingbullslogowhite.webp",
		Image:         "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/common/f1/2025/racingbulls/2025racingbullscarright.webp",
		Name:          "Racing Bulls",
		Nationality:   "Italian",
		TeamColor:     "#2345AB",
	},
	{
		ConstructorID: "red_bull",
		Icon:          "https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000000/common/f1/2025/redbullracing/2025redbullracinglogowhite.webp",
		Image:         "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/common/f1/2025/redbullracing/2025redbullracingcarright.webp",
		Name:          "Red Bull Racing",
		Nationality:   "Austrian",
		TeamColor:     "#003282",
	},
	{
		ConstructorID: "sauber",
		Icon:          "https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000000/common/f1/2025/kicksauber/2025kicksauberlogowhite.webp",
		Image:         "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/common/f1/2025/kicksauber/2025kicksaubercarright.webp",
		Name:          "Kick Sauber",
		Nationality:   "Swiss",
		TeamColor:     "#006300",
	},
	{
		ConstructorID: "williams",
		Icon:          "https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000000/common/f1/2025/williams/2025williamslogowhite.webp",
		Image:         "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/common/f1/2025/williams/2025williamscarright.webp",
		Name:          "Williams",
		Nationality:   "British",
		TeamColor:     "#000681",
	},
}
